version: 2
updates:
  - package-ecosystem: docker
    labels:
      - "Actor:Dependabot"
      - "Deps:Docker"
      - "Luna:Automerge"
    commit-message:
      prefix: "chore(deps):"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: pip
    labels:
      - "Actor:Dependabot"
      - "Deps:Python"
    commit-message:
      prefix: "chore(deps):"
    directory: "/root"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"
    ignore:
      # Upstream is horrible at following semver specs
      # They change interface names and even replace entire repos
      # to a new ones between patch releases!
      - dependency-name: "protonvpn-cli"

  # Actions
  - package-ecosystem: github-actions
    labels:
      - "Actor:Dependabot"
      - "Deps:Actions"
    commit-message:
      prefix: "ci(deps):"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"
