version: '3.4'
services:
  protonvpn:
    container_name: protonvpn
    environment:
      TZ: "Europe/Berlin"
      PROTONVPN_PROTOCOL: udp
      PROTONVPN_COUNTRY: NL
    env_file:
      - .protonvpn.env
    image: tprasadtp/protonvpn
    restart: unless-stopped
    networks:
      - internet
      - traefik
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 1.1.1.3
      - 1.0.0.3
    dns_search:
      - cluster.local
      - scv.cluster.local
      - lan
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - protonvpn:/root/.pvpn-cli
  pyload:
    depends_on:
      - protonvpn
    container_name: pyload
    environment:
      TZ: "Europe/Berlin"
      PGID: "1000"
      PUID: "1000"
    image: linuxserver/pyload:latest
    restart: unless-stopped
    userns_mode: host
    network_mode: service:protonvpn
    # networks:
    #   - web
    #   - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - ./downloads/:/downloads/:rw
  caddy:
    container_name: caddy
    image: caddy:2.0.0
    command: caddy reverse-proxy --change-host-header  --from :80 --to protonvpn:8000
    depends_on:
      - pyload
    environment:
      TZ: "Europe/Berlin"
    restart: unless-stopped
    networks:
      - traefik
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pyload.rule=Host(`pyload.lan`)"
      - "traefik.http.routers.pyload.tls=true"
      - "traefik.http.routers.pyload.entrypoints=websecure"
      - "traefik.http.services.pyload.loadbalancer.server.port=80"
volumes:
  config:
  protonvpn:
networks:
  internet:
  traefik:
    internal: true
