apiVersion: v1
kind: Pod
metadata:
  name: runs-over-vpn
spec:
  containers:
  - name: protonvpn
    image: ghcr.io/tprasadtp/protonvpn:2.2.6
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
    volumeMounts:
      - mountPath: /dev/net/tun
        name: dev-net-tun
  - name: pyload
    image: linuxserver/pyload
    ports:
      - containerPort: 8000
    volumeMounts:
      - mountPath: /mnt/downloads
        name: downloads
  volumes:
    - hostPath:
        path: /dev/net/tun
      name: dev-net-tun
    - hostPath:
        path: /dev/net/tun
      name: downloads
